CREATE TABLE favorites (
    id INT PRIMARY KEY AUTO_INCREMENT,
    course_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
); 